name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  DotNetVersion: "8.0.401"
  BuildParameters: "/v:Minimal /consoleLoggerParameters:NoSummary /p:Configuration=Release /p:BuildVersion=${{ github.run_id }} /p:BuildBranch=${{ github.ref }}"

jobs:
  build-windows-2022:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[17.0,18.0)'

    - name: Build VS2022
      run: msbuild /restore ${{ env.BuildParameters }} /p:VSVersion=2022 Rhino.VisualStudio.Windows\Rhino.VisualStudio.Windows.csproj /bl:artifacts/log/Build.Windows.2022.binlog

    - name: Upload extensions
      uses: actions/upload-artifact@v4
      with:
        name: extensions-windows
        path: artifacts/Release/*.vsix

    - name: Upload templates
      uses: actions/upload-artifact@v4
      with:
        name: templates
        path: artifacts/bin/Rhino.Templates/Release/*.nupkg

    - name: Upload log files
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: log
        path: artifacts/log/**/*

  publish:
    needs: [ build-windows-2022 ]
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Add extensions to release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            extensions-windows/*.vsix
            templates/*.nupkg
